#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleObjCHTTPFoundation-import-private.h
src/reflect/_MulleObjCHTTPFoundation-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleObjCHTTPFoundation-import.h
src/reflect/_MulleObjCHTTPFoundation-include.h
)

set( PUBLIC_HEADERS
src/MulleHTTPHeaderParser.h
src/MulleHTTP.h
src/MulleObjCHTTPFoundation.h
src/MulleObjCLoader+MulleObjCHTTPFoundation.h
src/NSDate+MulleHTTP.h
src/NSString+HTML.h
src/NSString+ListComponents.h
src/import.h
src/include.h
)

