#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleHTTPHeaderParser.m
src/MulleObjCHTTPFoundation.m
src/NSDate+MulleHTTP.m
src/NSString+HTML.m
src/NSString+ListComponents.m
src/NSURL+HTTP.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCHTTPFoundation.m
)
