/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_HTTP_VERSION)
# if MULLE_HTTP_VERSION < ((0 << 20) | (1 << 8) | 4)
#  error "mulle-http is too old"
# endif
# if MULLE_HTTP_VERSION >= ((0 << 20) | (2 << 8) | 0)
#  error "mulle-http is too new"
# endif
#endif

#if defined( MULLE_OBJC_INET_FOUNDATION_VERSION)
# if MULLE_OBJC_INET_FOUNDATION_VERSION < ((0 << 20) | (18 << 8) | 3)
#  error "MulleObjCInetFoundation is too old"
# endif
# if MULLE_OBJC_INET_FOUNDATION_VERSION >= ((0 << 20) | (19 << 8) | 0)
#  error "MulleObjCInetFoundation is too new"
# endif
#endif
