/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleObjCHTTPFoundation_include_h__
#define _MulleObjCHTTPFoundation_include_h__

// How to tweak the following mulle-http #include
//    remove:             `mulle-sourcetree mark mulle-http no-header`
//    rename:             `mulle-sde dependency|library set mulle-http include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mulle-http [no-]import`
//    toggle localheader: `mulle-sourcetree mark mulle-http [no-]localheader`
//    toggle public:      `mulle-sourcetree mark mulle-http [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-http [no-]require`
//    remove for os:      `mulle-sourcetree mark mulle-http no-os-<osname>`
# if defined( __has_include) && __has_include("mulle-http.h")
#   include "mulle-http.h"   // mulle-http
# else
#   include <mulle-http/mulle-http.h>   // mulle-http
# endif

#endif
