/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_http_foundation_include_h__
#define _mulle_objc_http_foundation_include_h__

// You can tweak the following #include with these commands.
// (Use BB851E0A-3CD2-4E83-B76D-87124F74F3E4 instead of mulle-http if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-http no-header`
//    rename:              `mulle-sde dependency|library set mulle-http include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-http <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-http [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-http [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-http [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-http no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-http/mulle-http.h>   // mulle-http

#endif
