/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_OBJC_INET_FOUNDATION_VERSION)
# if MULLE_OBJC_INET_FOUNDATION_VERSION < ((0 << 20) | (18 << 8) | 5)
#  error "MulleObjCInetFoundation is too old"
# endif
# if MULLE_OBJC_INET_FOUNDATION_VERSION >= ((0 << 20) | (19 << 8) | 0)
#  error "MulleObjCInetFoundation is too new"
# endif
#endif
