/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove MulleObjCInetFoundation`
// (Use E98016C0-6BAC-41FC-A2B9-7376631179F8 instead of MulleObjCInetFoundation, if there are duplicate entries)
//
// You can tweak the following #import with these commands:
//    remove #import      : `mulle-sde dependency mark MulleObjCInetFoundation no-header`
//    rename              : `mulle-sde dependency|library set MulleObjCInetFoundation include whatever.h`
//    reorder             : `mulle-sde dependency move MulleObjCInetFoundation <up|down>`
//    toggle #import      : `mulle-sde dependency mark MulleObjCInetFoundation [no-]import`
//    toggle public       : `mulle-sde dependency mark MulleObjCInetFoundation [no-]public`
//    toggle optional     : `mulle-sde dependency mark MulleObjCInetFoundation [no-]require`
//    remove for platform : `mulle-sde dependency mark MulleObjCInetFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCInetFoundation/MulleObjCInetFoundation.h>   // MulleObjCInetFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCHTTPFoundation-include.h")
#  include "_MulleObjCHTTPFoundation-include.h"
# endif
#endif

