/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_objc_http_foundation_versioncheck_h__
#define mulle_objc_http_foundation_versioncheck_h__

#if defined( MULLE_OBJC_INET_FOUNDATION_VERSION)
# ifndef MULLE_OBJC_INET_FOUNDATION_VERSION_MIN
#  define MULLE_OBJC_INET_FOUNDATION_VERSION_MIN  ((0 << 20) | (18 << 8) | 6)
# endif
# ifndef MULLE_OBJC_INET_FOUNDATION_VERSION_MAX
#  define MULLE_OBJC_INET_FOUNDATION_VERSION_MAX  ((0 << 20) | (19 << 8) | 0)
# endif
# if MULLE_OBJC_INET_FOUNDATION_VERSION < MULLE_OBJC_INET_FOUNDATION_VERSION_MIN
#  error "MulleObjCInetFoundation is too old"
# endif
# if MULLE_OBJC_INET_FOUNDATION_VERSION >= MULLE_OBJC_INET_FOUNDATION_VERSION_MAX
#  error "MulleObjCInetFoundation is too new"
# endif
#endif

#endif
