      { @selector( MulleObjCLoader), @selector( MulleFoundation) },      // 47a9beb6;MulleObjCLoader;46ed3b36;MulleFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 47a9beb6;MulleObjCLoader;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleHTTPHeaderParser), MULLE_OBJC_NO_CATEGORYID },      // 33ba7405;MulleHTTPHeaderParser;;
      { @selector( NSDate), @selector( MulleHTTP) },      // cfcedd21;NSDate;72f647ea;MulleHTTP
      { @selector( NSString), @selector( ListComponents) },      // 1994a171;NSString;65ed93d3;ListComponents
      { @selector( NSString), @selector( MulleHTMLEscaping) },      // 1994a171;NSString;721b13f4;MulleHTMLEscaping
      { @selector( NSURL), @selector( HTTP) },      // 6b1e8f73;NSURL;6b67da50;HTTP
