#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_HEADERS
src/MulleHTTPHeaderParser.h
src/MulleHTTP.h
src/MulleObjCHTTPFoundation.h
src/MulleObjCLoader+MulleObjCHTTPFoundation.h
src/NSDate+MulleHTTP.h
src/NSString+HTML.h
src/NSString+ListComponents.h
src/http_parser.h
src/import.h
src/include.h
)

